source 'https://rubygems.org'

#ruby=ruby-2.1.5
#ruby-gemset=tablifier

gem 'rails', '4.2.7'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'tablifier', path: '../..'
